import { mockGroups, mockPlaces, mockVisits } from '../data/mock'; import { supabase, useMockData } from '../lib/supabase/client'; import type { ExportBundle, Group, Place, Visit, VisitFormValue } from '../types'; import type { TakeoutPlace } from '../features/takeout/takeoutParser';
const localKey = 'spotory-demo-visits'; const localPlacesKey = 'spotory-demo-places'; const canUseDb = () => Boolean(supabase) && !useMockData;
const localVisits = () => { try { return JSON.parse(localStorage.getItem(localKey) || '[]') as Visit[]; } catch { return []; } };
const standaloneLocalPlaces = () => { try { return JSON.parse(localStorage.getItem(localPlacesKey) || '[]') as Place[]; } catch { return []; } };
export const repository = {
  async listVisits(): Promise<Visit[]> { if (!canUseDb()) return [...localVisits(), ...mockVisits]; const { data, error } = await supabase!.from('visits').select('*, place:places(*), photos(*)').order('visited_at', { ascending:false }); if (error) throw error; const visits=data as Visit[]; await Promise.all(visits.flatMap(visit=>(visit.photos||[]).map(async photo=>{const{data:signed,error:signedError}=await supabase!.storage.from('visit-photos').createSignedUrl(photo.storage_path,3600);if(!signedError)photo.signed_url=signed.signedUrl;}))); return visits; },
  async getVisit(id:string) { return (await this.listVisits()).find(v => v.id === id) ?? null; },
  async listPlaces(): Promise<Place[]> { if (!canUseDb()) return [...standaloneLocalPlaces(), ...localVisits().flatMap(v => v.place ? [v.place] : []), ...mockPlaces]; const { data,error } = await supabase!.from('places').select('*').order('name'); if(error) throw error; return data as Place[]; },
  async listGroups(): Promise<Group[]> { if (!canUseDb()) return mockGroups; const { data,error } = await supabase!.from('groups').select('*'); if(error) throw error; return data as Group[]; },
  async saveVisit(value:VisitFormValue, userId:string, id?:string): Promise<Visit> { if (!canUseDb()) { const place:Place = { ...value.place, id:value.place.id || crypto.randomUUID(), created_by:userId, created_at:new Date().toISOString() }; const visit:Visit={ ...value, id:id||crypto.randomUUID(), place_id:place.id, user_id:userId, created_at:new Date().toISOString(), place }; const all=localVisits().filter(v=>v.id!==id); localStorage.setItem(localKey,JSON.stringify([visit,...all])); return visit; }
    let placeId=value.place.id; if(!placeId){ const {data,error}=await supabase!.from('places').insert({...value.place,created_by:userId}).select().single(); if(error) throw error; placeId=data.id; }
    const payload={place_id:placeId,visited_at:value.visited_at,rating:value.rating,comment:value.comment,visibility:value.visibility,is_favorite:value.is_favorite,is_wishlist:value.is_wishlist,category:value.category}; let visitId=id; if(id){const{error}=await supabase!.from('visits').update(payload).eq('id',id);if(error)throw error;}else{const{data,error}=await supabase!.rpc('create_visit',{p_place_id:placeId!,p_visited_at:value.visited_at,p_rating:value.rating,p_comment:value.comment,p_visibility:value.visibility,p_is_favorite:value.is_favorite,p_is_wishlist:value.is_wishlist,p_category:value.category});if(error)throw error;visitId=data as string;} if(value.visibility==='group'){ await supabase!.from('visit_groups').delete().eq('visit_id',visitId!); if(value.group_ids.length) await supabase!.from('visit_groups').insert(value.group_ids.map(group_id=>({visit_id:visitId!,group_id}))); } const{data,error}=await supabase!.from('visits').select('*, place:places(*)').eq('id',visitId!).single();if(error)throw error;return data as Visit; },
  async uploadPhotos(visitId:string,userId:string,files:File[]){if(!files.length||!canUseDb())return;for(const[sort_order,file]of files.entries()){const id=crypto.randomUUID();const storage_path=`${userId}/${visitId}/${id}.webp`;const{error:uploadError}=await supabase!.storage.from('visit-photos').upload(storage_path,file,{contentType:file.type||'image/webp',upsert:false});if(uploadError)throw uploadError;const image=await createImageBitmap(file);const{error}=await supabase!.from('photos').insert({id,visit_id:visitId,user_id:userId,storage_path,sort_order,width:image.width,height:image.height,file_size:file.size,mime_type:file.type||'image/webp'});image.close();if(error){await supabase!.storage.from('visit-photos').remove([storage_path]);throw error;}}},
  async deleteVisit(id:string) { if(!canUseDb()){localStorage.setItem(localKey,JSON.stringify(localVisits().filter(v=>v.id!==id)));return;} const {error}=await supabase!.from('visits').delete().eq('id',id); if(error) throw error; },
  async createGroup(name:string,userId:string){ if(!canUseDb()) return {id:crypto.randomUUID(),name,owner_id:userId,role:'owner' as const,created_at:new Date().toISOString()}; const {data,error}=await supabase!.from('groups').insert({name,owner_id:userId}).select().single(); if(error)throw error; return data as Group; },
  async importPlaces(values:TakeoutPlace[],userId:string){ const existing=await this.listPlaces(); const normalize=(value:string|null|undefined)=>value?.trim().toLocaleLowerCase('ja-JP')||''; const keys=new Set(existing.map(place=>`${normalize(place.name)}\u0000${normalize(place.address)}`)); const unique=values.filter(value=>{const key=`${normalize(value.name)}\u0000${normalize(value.address)}`;if(keys.has(key))return false;keys.add(key);return true;}); const rows=unique.map(({key:_,...place})=>({...place,created_by:userId})); if(!canUseDb()){const now=new Date().toISOString();const created=rows.map(place=>({...place,id:crypto.randomUUID(),created_at:now}));localStorage.setItem(localPlacesKey,JSON.stringify([...created,...standaloneLocalPlaces()]));return{created:created.length,skipped:values.length-created.length};} if(rows.length){const{error}=await supabase!.from('places').insert(rows);if(error)throw error;}return{created:rows.length,skipped:values.length-rows.length};},
  async exportData():Promise<ExportBundle>{ const [visits,places,groups]=await Promise.all([this.listVisits(),this.listPlaces(),this.listGroups()]); return {exported_at:new Date().toISOString(),profile:null,visits,places,groups}; }
};
