import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';
import type { User } from '@supabase/supabase-js'; import { isSupabaseConfigured, supabase, useMockData } from '../../lib/supabase/client';
type AuthValue={user:User|null;loading:boolean;configured:boolean;signInWithEmail:(email:string)=>Promise<void>;signInWithGoogle:()=>Promise<void>;signOut:()=>Promise<void>};
const AuthContext=createContext<AuthValue|null>(null);
const demoUser={id:'demo-user',email:'demo@spotory.local',user_metadata:{display_name:'デモユーザー'},app_metadata:{},aud:'authenticated',created_at:new Date(0).toISOString()} as User;
export function AuthProvider({children}:{children:ReactNode}){const [user,setUser]=useState<User|null>(useMockData?demoUser:null);const[loading,setLoading]=useState(isSupabaseConfigured&&!useMockData);
 useEffect(()=>{if(!supabase||useMockData){setLoading(false);return;} supabase.auth.getSession().then(({data})=>{setUser(data.session?.user??null);setLoading(false);}); const{data}=supabase.auth.onAuthStateChange((_event,session)=>setUser(session?.user??null));return()=>data.subscription.unsubscribe();},[]);
 const value=useMemo<AuthValue>(()=>({user,loading,configured:isSupabaseConfigured||useMockData,signInWithEmail:async(email)=>{if(!supabase)throw new Error('Supabaseが未設定です');const{error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:location.href.split('#')[0]}});if(error)throw error;},signInWithGoogle:async()=>{if(!supabase)throw new Error('Supabaseが未設定です');const{error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.href.split('#')[0]}});if(error)throw error;},signOut:async()=>{if(useMockData){setUser(null);return;}await supabase?.auth.signOut();}}),[user,loading]); return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>}
export const useAuth=()=>{const value=useContext(AuthContext);if(!value)throw new Error('AuthProvider is missing');return value};
